

data:
  num_classes: 10
  train_set_size: 5000 # Pairs
  train_set_alpha: 0.5 # How much "image 1" overlays "image 2"
  val_set_size: 10000 # Single examples

model:
  input_dim: (32,32,3)

train:
  batch_size: 32
  epochs: 10
  loss_function: 'binary_crossentropy'
  optimizer: 'adam'
  learning_rate: 0.002
